// constants/client.constants.ts
import { Client, NewClientForm } from '../types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 1,
    name: "Acme Corp",
    info: "B2B SaaS for logistics. Based in NY.",
    logo: '',
    industry: "Logistics",
    links: ["https://acmecorp.com", "https://twitter.com/acmecorp"],
    niche: "Supply Chain Automation",
    businessAge: "5 years",
    description: "Acme Corp provides cloud-based logistics solutions for enterprises.",
    coreProducts: ["LogiTrack", "FleetSync"],
    idealCustomer: "Large logistics companies",
    brandEmotion: "Reliable, Innovative",
    uniqueSelling: "Real-time tracking with AI optimization",
    mainGoal: "Expand to Europe",
    competitors: ["Flexport", "Project44"],
    inspo: ["Amazon Logistics", "DHL"],
    brandColors: "#2563eb, #181A20",
    fontUsed: "Inter, Arial"
  },
  {
    id: 2,
    name: "Banana Media",
    info: "Cebu",
    logo: '',
    industry: "Marketing",
    links: ["https://bananamedia.com"],
    niche: "E-commerce Growth",
    businessAge: "3 years",
    description: "Helping online stores grow with paid ads and content.",
    coreProducts: ["AdBoost", "ContentPro"],
    idealCustomer: "Shopify store owners",
    brandEmotion: "Energetic, Creative",
    uniqueSelling: "ROI-focused ad campaigns",
    mainGoal: "Double client ROAS",
    competitors: ["Hawke Media", "Disruptive Advertising"],
    inspo: ["Gymshark", "Allbirds"],
    brandColors: "#FFD600, #23262F",
    fontUsed: "Montserrat, Helvetica"
  },
  {
    id: 3,
    name: "Zenith Health",
    info: "Private clinic network in California.",
    logo: '',
    industry: "Healthcare",
    links: ["https://zenithhealth.com"],
    niche: "Private Clinics",
    businessAge: "10 years",
    description: "Multi-location clinics offering family and urgent care.",
    coreProducts: ["Family Care", "Urgent Care"],
    idealCustomer: "Families in California",
    brandEmotion: "Caring, Trustworthy",
    uniqueSelling: "Same-day appointments",
    mainGoal: "Increase patient retention",
    competitors: ["One Medical", "Carbon Health"],
    inspo: ["Kaiser Permanente"],
    brandColors: "#00BFAE, #F1F5F9",
    fontUsed: "Roboto, Arial"
  }
];

export const INITIAL_FORM_STATE: NewClientForm = {
  name: '',
  info: '',
  logo: null,
  logoUrl: '',
  industry: '',
  links: '',
  niche: '',
  businessAge: '',
  description: '',
  coreProducts: '',
  idealCustomer: '',
  brandEmotion: '',
  uniqueSelling: '',
  mainGoal: '',
  competitors: '',
  inspo: '',
  brandColors: '',
  brandColorsFile: null,
  brandColorsFileUrl: '',
  brandGuideFile: null,
  brandGuideFileUrl: '',
  fontUsed: ''
};