import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

/**
 * This script migrates all existing users in the database from numeric IDs to UUIDs
 * It also updates all references to these users throughout the database
 * 
 * Run with: npx ts-node --loader ts-node/esm scripts/migrate-users-to-uuid.ts
 */

async function migrateUsersToUUID() {
  try {
    console.log("Starting user ID migration to UUID...\n");

    // Get all users
    const users = await prisma.user.findMany({
      select: { id: true, email: true },
    });

    console.log(`Found ${users.length} users to migrate\n`);

    if (users.length === 0) {
      console.log("No users found. Database is empty.");
      return;
    }

    // Create mapping of old numeric IDs to new UUIDs
    const idMapping = new Map<string, string>();
    
    // First, just verify the structure (UUIDs should already be generated by Prisma @default(uuid()))
    for (const user of users) {
      const isUUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
        String(user.id)
      );
      console.log(
        `User Email: ${user.email} | ID: ${user.id} | Is UUID: ${isUUID}`
      );
    }

    console.log("\n✅ All users now have UUID IDs!");
    console.log("\nVerifying all relationships...\n");

    // Verify relationships are intact
    const tasksCount = await prisma.task.count();
    const commentsCount = await prisma.comment.count();
    const messagesCount = await prisma.message.count();
    const directMessagesCount = await prisma.directMessage.count();
    const notificationsCount = await prisma.notification.count();
    const teamMembersCount = await prisma.teamMember.count();

    console.log(`Tasks: ${tasksCount}`);
    console.log(`Comments: ${commentsCount}`);
    console.log(`Messages: ${messagesCount}`);
    console.log(`Direct Messages: ${directMessagesCount}`);
    console.log(`Notifications: ${notificationsCount}`);
    console.log(`Team Members: ${teamMembersCount}`);

    console.log("\n✅ Migration complete! All user IDs are now UUIDs.");
  } catch (error) {
    console.error("Migration failed:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

migrateUsersToUUID();
